#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"2"
echo "==============================================" | lolcat
echo $lred"1." $white "LITESPAM"
echo $lred"2." $white "GCOSPAM"
echo $lred"3." $white "MULTISPAM"
echo $lred"4." $white "SPAM GRAB"
echo $lred"5." $white "SPAM SENI TOPENG"
echo $lred"6." $white "BOM MAIL"
echo $lred"7." $white "SPAZ SMS"
echo $lred"8." $white "SPAM JD.ID"
echo $lred"9." $white "BAJINGANV6"
echo $lred"10." $white"BETOOLS"
echo $lred"11." $white"LAZYMUX"
echo $lred"12." $white"DAIJOUBU"
echo $lred"13." $white"MR.CAKIL"
echo $lred"14." $white"4WSEC TOOLS"
echo $lred"15." $white"MR.RV1.1"
echo $lred"16." $white"X NOT FOUND"
echo $lred"17." $white"TOOLKIT"
echo $lred"18." $white"ERROR CYBER TOOLS"
echo $lred"19." $white"TU4N B4DUT"
echo $lred"20." $white"MBF"
echo $lred"21." $white"INSTAHACK"
echo $lred"22." $white"WA sec"
echo $lred"23." $white"METASPLOIT"
echo $lred"24." $white"A-RAT"
echo $lred"25." $white"BRUTAL"
echo "=============================================" | lolcat
echo $lred"0." $white "EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 3"
echo $lred"c." $white "page 4"
echo $lred"d." $white "page 5"
echo $lred"e." $white "page 6"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;

if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/4L13199/LITESPAM
cd LITESPAM
echo "done!" | selesai
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Amriez/gcospam
cd gcospam
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pkg install python
git clone https://github.com/Kereh/MultiSpam
cd MultiSpam
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install requests
git clone http://github.com/p4kl0nc4t/Spammer-Grab
cd Spammer-Grab
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2 php
pip2 install requests
apt install nano
git clone https://github.com/Senitopeng/SpamSms.git
cd SpamSms
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install git python2 && pip2 install argparse requests
git clone https://github.com/p4kl0nc4t/Spammer-Email
cd Spammer-Email
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python 2
git clone https://github.com/Gameye98/SpazSMS
cd SpazSMS
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt update
pkg install php
pkg install curl
curl https://pastebin.com/raw/nXT3BVS6 -o jdid.php
echo "done!" | lolcat
sleep 0.5
clear
cd $HOME/zbl
sh 1
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install cowsay && pkg install termcolor
git clone https://github.com/DarknessCyberTeam/BAJINGANv6
cd BAJINGANv6
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
clear
git clone https://github.com/mzubaili/betools
cd betools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Gameye98/Lazymux
cd Lazymux
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/alintamvanz/diejoubu
cd diejoubu
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/mrcakil/Mrcakil.git
cd Mrcakil
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/aryanrtm/4wsectools
cd 4wsectools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/MR_R225/Mr.Rv1.1
cd Mr.Rv1.1
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/hatakecnk/xNot_Found
cd xNot_Found
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Rajkumrdusad/Tool-Kit
cd Tool-Kit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/MrKeepSmile/errorcybertool.git
cd errorcybertool
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python python2 curl vim 
pkg install php
pip2 install lolcat
git clone https://github.com/TUANB4DUT/TOOLSINSTALLERv3
cd TOOLSINSTALLERv3
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 20 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2 && pkg install wget 
pip2 install mechanize && pip2 install requests 
git clone https://github.com/tikuskecil/multi-bruteforce-facebook
cd multi-bruteforce-facebook
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install requests
git clone https://github.com/avramit/instahack
cd instahack
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install curl
git clone http://github.com/soracyberteam/what-sexploit
cd what-sexploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install curl
curl -LO https://raw.githubusercontent.com/Hax4us/Metasploit_termux/master/metasploit.sh
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Xi4u7/A-Rat.git
cd A-Rat
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Screetsec/Brutal
cd Brutal
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/1
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 97 ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/1
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi