#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"3"
echo "==============================================" | lolcat
echo $lred"1." $white "WPSPLOIT"
echo $lred"2." $white "WEBSPLOIT"
echo $lred"3." $white "ROUTERSPLOIT"
echo $lred"4." $white "ASTRNMAP"
echo $lred"5." $white "TERMUX-STYLING-SHELL-SCRIPT"
echo $lred"6." $white "BOT FB BANG DJON"
echo $lred"7." $white "WEEMAN"
echo $lred"8." $white "TERMUX-UBUNTU"
echo $lred"9." $white "DSSS"
echo $lred"10." $white"SLOWROSIS"
echo $lred"11." $white"GOLDEN EYE"
echo $lred"12." $white"PLANET-WORK-DDOS"
echo $lred"13." $white"BLACK-HYDRA"
echo $lred"14." $white"CUPP"
echo $lred"15." $white"1337HASH"
echo $lred"16." $white"INDONESIAN-WORDLIST"
echo $lred"17." $white"WEBDAV"
echo $lred"18." $white"SQL-LOKMED"
echo $lred"19." $white"ZONES"
echo $lred"20." $white"COMMIX"
echo $lred"21." $white"KNOCK-MAIL"
echo $lred"22." $white"HAC"
echo $lred"23." $white"SPIDER-BOT"
echo $lred"24." $white"KALI-NETHUNTER"
echo $lred"25." $white"TERMUX-FEDORA"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 4"
echo $lred"d." $white "page 5"
echo $lred"e." $white "page 6"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;.
if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone git clone https://github.com/m4ll0k/wpsploit
cd wpsploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install scapy
git clone https://github.com/The404Hacking/websploit
cd websploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install requests
git clone https://github.com/reverse-shell/routersploit
cd routersploit
pip2 install -r requirements.txt termux-fix-shebang rsf.py
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Gameye98/AstraNmap
cd AstraNmap
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://gitbub.com/BagazMukti/Termux-Styling-Shell-Script
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Senitopeng/BotFbBangDjon.git
cd BotFbBangDjon
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/evait-security/weeman
cd weeman
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install wget
pkg install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd termux-ubuntu
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/stamparm/DSSS
cd DSSS
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/gkbrk/slowloris
cd slowloris
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 11 ]
then
clear
echo "menginstall" | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/jseidl/GoldenEye
cd GoldenEye
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Hydra7/Planetwork-DDOS
cd Planetwork-DDOS
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install hydra
pkg install python2
git clone https://github.com/Gameye98/Black-Hydra
cd Black-Hydra
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Mebus/cupp
cd cupp
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Gameye98/1337Hash
cd 1337Hash
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/geovedi/indonesian-wordlist
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2 openssl curl libcurl
pip2 install urllib3 chardet certifi idna requests
mkdir ~/webdav
curl -k -O http://override.waper.co/files/webdav.txt;mv
webdav.txt ~/webdav/webdav.py
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install urllib2
git clone https://github.com/Anb3rSecID/sqlokmed
cd sqlokmed
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Cvar1984/zones
cd zones
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 20 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/commixproject/commix
cd commix
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install validate_email pyDNS
git clone https://github.com/4w4k3/KnockMail
cd KnockMail
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Cvar1984/Hac
cd Hac
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Cvar1984/SpiderBot
cd Spider-Bot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Hax4us/Nethunter-In-Termux
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install wget
wget https://raw.githubusercontent.com/nmilosev/termux-fedora/master/termux-fedora.sh
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/2
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 97 ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/2
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi