#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"4"
echo "==============================================" | lolcat
echo $lred"1." $white "TXTOOLS"
echo $lred"2." $white "BINGOO"
echo $lred"3." $white "TERMUX-A"
echo $lred"4." $white "GADO-GADO"
echo $lred"5." $white "IES DEFACE"
echo $lred"6." $white "IP GEOLOCATION"
echo $lred"7." $white "VI-SQL"
echo $lred"8." $white "IPDDOS"
echo $lred"9." $white "HASHER"
echo $lred"10." $white"PHISING GAME"
echo $lred"11." $white"BREACHER"
echo $lred"12." $white"SOCIAL-FISH"
echo $lred"13." $white"MD5-CRACK"
echo $lred"14." $white"PEMULUNG-BTC"
echo $lred"15." $white"KO-DORK"
echo $lred"16." $white"LHST"
echo $lred"17." $white"THE-FAT-RAT"
echo $lred"18." $white"CMSMAP"
echo $lred"19." $white"NGROK"
echo $lred"20." $white"BRUTE-FORCE-GMAIL"
echo $lred"21." $white"LOKOMEDIA"
echo $lred"22." $white"JOOMSCAN"
echo $lred"23." $white"VULN-SCANNER"
echo $lred"24." $white"HN-INSTALLER"
echo $lred"25." $white"FUCKING-RAT"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 5"
echo $lred"e." $white "page 6"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;.
if [ $a = 1 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/kuburan/txtool
cd txtool
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 2 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Hood3dRob1n/BinGoo
cd BinGoo
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 3 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install termux-api
apt install php
git clone https://github.com/Cvar1984/Termux-A.git
cd Termux-A
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 4 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install ruby
pip2 install lolcat
git clone https://github.com/Senitopeng/GadoGado.git
cd GadoGado
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 5 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/ALX-04/iesDEFACE
cd iesDEFACE
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 6 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/maldevel/IPGeoLocation.git
cd IPGeoLocation
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 7 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/blackvkng/viSQL
cd viSQL
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 8 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/CiKu370/ipddos.git
cd ipddos
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 9 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/CiKu370/hasher.git
cd hasher
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 10 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/senitopeng/PhisingGame.git
cd PhisingGame
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 11 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/UltimateHackers/Breacher.git
cd Breacher
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 12 ]
then 
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Lexiie/SocialFish.git
cd SocialFish
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 13 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/CiKu370/md5-crack.git
cd md5-crack
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 14 ]
then 
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Cvar1984/pemulungBTC.git
cd pemulungBTC
echo "menginstall... " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 15 ]
then
clear 
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/ciku370/ko-dork.git
cd ko-dork
echo "done! " | lolcat 
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 16 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/CiKu370/lhst
cd lhst
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 17 ]
then 
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Screetsec/TheFatRat.git
cd TheFatRat
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 18 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Dionach/CMSmap.git
cd CMSmap
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 19 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install wget
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 20 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/JamesAndresCM/Brute_force_gmail
cd Brute_force_gmail
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 21 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install php
pkg install wget
wget https://pastebin.com/raw/sPpJRjCZ -O lokomedia.php
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install perl
git clone https://github.com/rezasp/joomscan.git
cd joomscan
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 23 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/kereh/VulnScaner
cd VulnScaner
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 24 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/kereh/HN-Installer
cd HN-Installer
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/kereh/Fucking-Rat
cd Fucking-Rat
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/3
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 97 ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/3
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi