#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"5"
echo "==============================================" | lolcat
echo $lred"1." $white "EZSPLOIT"
echo $lred"2." $white "DIRSEARCH"
echo $lred"3." $white "SPAM-MAIL-HONEY-POT"
echo $lred"4." $white "KILLR"
echo $lred"5." $white "DEPENDENCIES"
echo $lred"6." $white "TERMUX-MPV"
echo $lred"7." $white "OWASP-NETTACKER"
echo $lred"8." $white "OWASP-ZSC"
echo $lred"9." $white "HASH-GENERATOR"
echo $lred"10." $white"OSIF"
echo $lred"11." $white"STR2BF"
echo $lred"12." $white"BFORCE"
echo $lred"13." $white"GALILEO"
echo $lred"14." $white"SMBRUTE"
echo $lred"15." $white"WPSEKU"
echo $lred"16." $white"HMAP"
echo $lred"17." $white"AUTO-REPORT-FB"
echo $lred"18." $white"DHCPDORF"
echo $lred"19." $white"DESKON-DEKSTOP"
echo $lred"20." $white"M4NG-ARP"
echo $lred"21." $white"WP-HUNTER"
echo $lred"22." $white"REMOTE-SHELL"
echo $lred"23." $white"LITESCRIPT"
echo $lred"24." $white"ZILCORILI"
echo $lred"25." $white"ASKT"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 6"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;.
if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/rand0m1ze/ezsploit
cd ezsploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python python2
git clone https://github.com/maurosoria/dirsearch.git
cd dirsearch.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install php
git clone https://github.com/whackashoe/php-spam-mail-honeypot.git
cd php-spam-mail-honeypot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install php
git clone https://github.com/whackashoe/killr.git
cd killr
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install php
git clone https://github.com/whackashoe/Human_Level_Control_through_Deep_Reinforcement_Learning.git
cd Human_Level_Control_through_Deep_Reinforcement_Learning
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install php
git clone https://github.com/Neo-Oli/Termux-Mpv.git
cd Termux-Mpv
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/zdresearch/OWASP-Nettacker
cd OWASP-Nettacker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/zdresearch/OWASP-ZSC
cd OWASP-ZSC
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/CiKu370/hash-generator
cd hash-generator
echo "done!" | lolcat
sleep 0.5
sh $HOME/zbl/4
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/CiKu370/OSIF
cd OSIF
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/CiKu370/str2bf
cd str2bf
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/YukersCreew/BForce
cd BForce
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/m4ll0k/Galileo
cd Galileo
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/m4ll0k/SMBrute
cd SMBrute
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/m4ll0k/WPSeku
cd WPSeku
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/Mebus/hmap
cd hmap
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install ruby
git clone https://github.com/gshofficialgithubindonesia/autoreport-fb
cd autoreport-fb
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 18 ]
then
clear
echo "menginstalll..." | lolcat
sleep 0.5
apt install golang
git clone https://github.com/Mebus/dhcpdorf
cd dhcpdorf
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
git clone https://github.com/Mebus/deskcon-desktop
cd deskcon-desktop
echo "menginstall..." | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 20 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/aryanrtm/m4ngARP
cd m4ngARP
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install perl
git clone https://github.com/aryanrtm/WP-Hunter
cd WP-Hunter
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install perl
git clone https://github.com/aryanrtm/Remote-Shell
cd Remote-Shell
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install perl
git clone https://github.com/4L13199/LITESCRIPT
cd LITESCRIPT
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install ruby
git clone https://github.com/b3-v3r/Zilcorili
cd Zilcorili
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install ruby
git clone https://github.com/b3-v3r/ASKT-AutoScriptKiddiesTool-
cd ASKT-AiroScriptKiddiesTool-
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/4
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 97 ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/4
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi