#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"6"
echo "==============================================" | lolcat
echo $lred"1." $white "BOT-EXPLOITER"
echo $lred"2." $white "INSTABOT"
echo $lred"3." $white "FB- BRUTE"
echo $lred"4." $white "EMAIL-HARVESTER"
echo $lred"5." $white "GDOG"
echo $lred"6." $white "PENTESKIT"
echo $lred"7." $white "CANISRUFUS"
echo $lred"8." $white "ETTERCAP-FOR-ANDROID"
echo $lred"9." $white "BLACK-NMAP"
echo $lred"10." $white"NMAP-FOR-ANDROID"
echo $lred"11." $white"1337RAT"
echo $lred"12." $white"ANYFED"
echo $lred"13." $white"KNOCK"
echo $lred"14." $white"VB-SCAN"
echo $lred"15." $white"DRAC-NMAP"
echo $lred"16." $white"BRUTESPLOIT"
echo $lred"17." $white"MICROSPLOIT"
echo $lred"18." $white"VEGILE"
echo $lred"19." $white"PH-EMAIL"
echo $lred"20." $white"REPOSCANNER"
echo $lred"21." $white"PAN-HUNT"
echo $lred"22." $white"ZAMBIE"
echo $lred"23." $white"TRACK-URL"
echo $lred"24." $white"DATASPLOIT"
echo $lred"25." $white"EMAIL-BOMB"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 5"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;.

if [ $a = 1 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/verluchie/bot-exploiter
cd bot-exploiter
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 2 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/verluchie/instabot.py
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 3 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
pip2 install --upgrade pip
pip2 install mechanize
git clone https://github.com/verluchie/fbbrute
cd fbbrute
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 4 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
pip2 install --upgrade pip
pip2 install requirements.txt
git clone https://github.com/maldevel/EmailHarvester
cd EmaulHarvester
echo "done! " | lolcat
sleep 0.5
clear 
sh $HOME/zbl/5
fi

if [ $a = 5 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
pip2 install --upgrade pip
pip2 install requirements.txt
git clone https://github.com/maldevel/gdog
cd gdog
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 6 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install sudo
git clone https://github.com/maldevel/PenTestKit
cd PenTesKit
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 7 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
pip2 install --upgrade pip
pip2 install requirements.txt
git clone https://github.com/maldevel/canisrufus
cd canisfurus
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 8 ]
then
clear
git clone https://github.com/Xi4u7/EttercapForAndroid
cd EttercapForAndroid
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 9 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Xi4u7/BlackNmap
cd BlackNmap
chmod 777 blacknmap
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 10 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Xi4u7/NMapForAndroid
cd NmapForAndroid
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 11 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Xi4u7/1337Rat
cd 1337Rat
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 12 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/nmilosev/anyfed
cd anyfed
chmod 777 anyfed
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 13 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
pkg install python2
pip2 install --upgrade pip
pip2 install requirements.txt
git clone https://github.com/guelfoweb/knock
cd knock
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 14 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/rezasp/vbscan
cd vbscan
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 15 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Screetsec/Dracnmap
cd Dracnmap
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 16 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Screetsec/BruteSploit
cd BruteSploit
chmod 77 BruteSploit 
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 17 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Screetsec/Microsploit
cd Microsploit
chmod 777 Microsploit
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 18 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/Screetsec/Vegile
cd Vegile
chmod 777 Vegile
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 19 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/Dionach/PhEmail
cd PhEmail
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 20 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/Dionach/reposcanner
cd reposcanner
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 21 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/Dionach/PANhunt
cd PANhunt
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi 

if [ $a = 22 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/zanyarjamal/zambie
cd zambie
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 23 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
git clone https://github.com/zanyarjamal/TrackUrl
cd TrackUrl
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi 

if [ $a = 24 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/zanyarjamal/DataSploit
cd DataSploit
echo "done! "
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 25 ]
then
clear
echo "menginstall... " | lolcat
sleep 0.5
apt install python2
git clone https://github.com/zanyarjamal/Email-bomber
cd Email-bomber
echo "done! " | lolcat
sleep 0.5
clear
sh $HOME/zbl/5
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 97 ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/5
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi