#!/bin/bash
#please_dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"7"
echo "==============================================" | lolcat
echo $lred"1." $white "IP-LOCATOR"
echo $lred"2." $white "ADMIN-FINDER"
echo $lred"3." $white "PYNMAP"
echo $lred"4." $white "SQLI-SCANNER"
echo $lred"5." $white "PORT-LOOKUP"
echo $lred"6." $white "TIC-TAC-TOE"
echo $lred"7." $white "FOLDER-LOCKER"
echo $lred"8." $white "XEROSPLOIT"
echo $lred"9." $white "WIFRESTI"
echo $lred"10." $white"SQLIV"
echo $lred"11." $white"CLICKNROOT"
echo $lred"12." $white"BLACK-MAIL"
echo $lred"13." $white"BLACK-TRACK"
echo $lred"14." $white"HASHCODE"
echo $lred"15." $white"DEC-ENC-HASH"
echo $lred"16." $white"HOST-CHECKER"
echo $lred"17." $white"MY-ENC"
echo $lred"18." $white"START-PHP"
echo $lred"19." $white"FACENOTIFY"
echo $lred"20." $white"NOTEFAST"
echo $lred"21." $white"SERVER-DOMAIN"
echo $lred"22." $white"MY-SERVER"
echo $lred"23." $white"RECON-NG-TERMUX"
echo $lred"24." $white"SETOOL-KIT"
echo $lred"25." $white"KALI-LINUX-FOR-TERMUX"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 5"
echo $lred"f." $white "page 7"
echo $lred"g." $white "page 8"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;

if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install perl
git clone https://github.com/zanyarjamal/IP-Locator
echo "done!"
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/the-c0d3r/admin-finder.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/the-c0d3r/pynmap
echo "doe!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/the-c0d3r/sqli-scanner
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/the-c0d3r/port-lookup
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/the-c0d3r/tic-tac-toe
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/the-c0d3r/folderlocker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/LionSec/xerosploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/LionSec/wifresti
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 10 ]
then
clear
echo "menginstalll..." | lolcat
sleep 0.5
apt install python2-dev clang libxml2-dev libxml-utils libxslt-dev
pip2 install --upgrade pip
pip2 install -r requirements.txt
git clone https://github.com/Lexiie/sqliv.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/evait-security/ClickNRoot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/kereh/BlackMail
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/kereh/BlackTrack
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/haijuga7/Hashcode
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/haijuga7/Dec-Enc-Hash
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/pirmansx/hostchecker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleeo 0.5
pkg install python2
git clone https://github.com/pirmansx/myenc
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/cyweb/StartPhp
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/cyweb/facenotify
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 20 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/cyweb/notefast
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 21 ]
then
clear
echo "memginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/cyweb/server_domains
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
git clone https://github.com/Rajkumrdusad/MyServer
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Techzindia/recon-ng_termux_by_viral
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Techzindia/setoolkit-for-termux
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install curl
curl -LO https://raw.githubusercontent.com/Techzindia/Kali-linux_For_Termux/master/Kali-linux-Termux
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/6
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/6
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi