#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"8"
echo "==============================================" | lolcat
echo $lred"1." $white "XSSTRIKE"
echo $lred"2." $white "HUE"
echo $lred"3." $white "NANO"
echo $lred"4." $white "ENTROPY"
echo $lred"5." $white "DECODIFY"
echo $lred"6." $white "SHELL-STACK"
echo $lred"7." $white "FB-VIDEO-DOWNLOADER"
echo $lred"8." $white "STABILIZER-BOT"
echo $lred"9." $white "REMBOT"
echo $lred"10." $white"TOUCHING-SKY"
echo $lred"11." $white"THANATOS"
echo $lred"12." $white"THANATOS-ARCHER"
echo $lred"13." $white"BRUTE-XSS"
echo $lred"14." $white"CSRF-POC-MAKER"
echo $lred"15." $white"SARAHAH-XSS-XPLOIT"
echo $lred"16." $white"PHP-BACK-CONNECTOR"
echo $lred"17." $white"XEIT-CYBER"
echo $lred"18." $white"BOX-SOSMED"
echo $lred"19." $white"CREW-BOT"
echo $lred"20." $white"BOX-SPAM"
echo $lred"21." $white"CAM-STREAM-V3"
echo $lred"22." $white"GOOGLE-DORK"
echo $lred"23." $white"VIRUS-CREATER"
echo $lred"24." $white"SPAM-MR.MSDV"
echo $lred"25." $white"SPAM BUKALAPAK"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 5"
echo $lred"f." $white "page 6"
echo $lred"g." $white "page 7"
echo $lred"h." $white "page 9"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;

if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python
git clone https://github.com/UltimateHackers/XSStrike
pip install requirements
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/UltimateHackers/hue
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/UltimateHackers/nano
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/UltimateHackers/Entropy
echo "done!" | lolcat
sleep 0.5
clear
sh $HIME/zbl/7
fi

if [ $a = 5 ]
then
clear
echo "mengunstall..." | lolcat
sleep 0.5
pkg install python
git clone https://github.com/UltimateHackers/Decodify
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Tuhinshubhra/shellstack
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Tuhinshubhra/Facebook-Video-Downloader
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/4shadoww/stabilizerbot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/4shadoww/RemBot
echo "done!" | lolcat
sleep 0.5
clear
sh $HONE/zbl/7
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/4shadoww/touchingsky
echo "menginstall..." | lolcat
sleep 0.5
sh $HOME/zbl/7
fi 

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/4shadoww/thanatos
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/4shadoww/thanatos-archer
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python 2
pip2 install colorama
pip2 install mechanize
git clone https://github.com/shawarkhanethicalhacker/BruteXSS
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/shawarkhanethicalhacker/csrfpocmaker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/shawarkhanethicalhacker/Sarahah-XSS-Exploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/shawarkhanethicalhacker/PHP-BackConnector
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/DaffaTakarai/XEIT_Cyber
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Xeit666h05t/BoxSosmed
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Xeit666h05t/CrewBot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 20 ]
then
clear
echo "menginstall .." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Xeit666h05t/BoxSpam
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/avramit/CamStream-V3
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/XG77Z10/Google-Dork
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
pip2 install mechanize
git clone https://github.com/ERROR4317/viruscreater.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 24 ]
then
clear
echo "done!" | lolcat
sleep 0.5
git clone https://github.com/mrmsdv/sdvspam.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone http://github.com/siputra12/prank
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/7
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/7
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/8
fi