#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"9"
echo "==============================================" | lolcat
echo $lred"1." $white "TERMUX-OH-MY-ZSH"
echo $lred"2." $white "AOC-SPAMMER"
echo $lred"3." $white "AL-MAUL-TOOLS"
echo $lred"4." $white "GREEN-REAPER"
echo $lred"5." $white "MX-TOOLS"
echo $lred"6." $white "AOC-VIRUS"
echo $lred"7." $white "AOC-DEFACE"
echo $lred"8." $white "AOC-TOOLS"
echo $lred"9." $white "MINI-TOOLS"
echo $lred"10." $white"V-TOOLS"
echo $lred"11." $white"TN-TOOLS"
echo $lred"12." $white"WIFI-HACKER"
echo $lred"13." $white"LITE-OTP"
echo $lred"14." $white"BOT-KUBIK"
echo $lred"15." $white"CC-GEN"
echo $lred"16." $white"BLACK-SPAM"
echo $lred"17." $white"EMAIL-ACCOUNT"
echo $lred"18." $white"NEW-SPAMMER"
echo $lred"19." $white"SHELL-PHISH"
echo $lred"20." $white"WIFI-PHISHER"
echo $lred"21." $white"MAPS"
echo $lred"22." $white"KTP-KK-GENERATE"
echo $lred"23." $white"TERMUX-LOGIN-V2FX"
echo $lred"24." $white"SCRIPT-DEFACE-CREATOR"
echo $lred"25." $white"WIFITE"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 5"
echo $lred"f." $white "page 6"
echo $lred"g." $white "page 7"
echo $lred"h." $white "page 8"
echo $lred"i." $white "page 10"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;

if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install curl
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 2 ]
then
clear
echo "meng8nstall..." | lolcat
sleep 0.5
git clone https://github.com/rootM3eX/AOCSPAMMER
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/rootM3eX/ALMAUL-Tools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Amriez/GreenReaper
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/rootM3eX/Mx-Tools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/rootM3eX/AOCVirus
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/Amriez/AOCDEFACE.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8 
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/rootM3eX/AOCTools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
pkg install python
git clone https://github.com/rootM3eX/MiniTools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php python
git clone https://github.com/rootM3eX/VTools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php python2
git clone https://github.com/rootM3eX/TNTools
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/esc0rtd3w/wifi-hacker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 13 ]
then
clear
echi "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://www.github.com/Cvar1984/LiteOTP
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install nano && pkg install php
git clone https://github.com/radenvodka/kubik-bot
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python python2
git clone https://github.com/kuurtb/ccgen.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2 php figlet
pkg install toilet nano ruby
pip2 install lolcat
git clone https://github.com/BLACheat78/spammblackheat78
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install perl
git clone https://github.com/x-xsystm/account
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/haijuga7/New-Spammer
cd New-Spammer
unzip spamm.zip
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 19 ]
then
clear
echo "memginstall..." | lolcat
sleep 0.5
git clone https://github.com/thelinuxchoice/shellphish
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 20 ]
then
clear
echo "done!" | lolcat
sleep 0.5
apt-get install python python-pip python-setuptools
pip install scapy
git clone https://github.com/wifiphisher/wifiphisher.git
echo "done!" | lolcat 
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install perl
git clone https://github.com/x-xsystm/maps.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/zerosvn/ktpkkgenerate
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Harisgitama/termux-loginv2fx.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Ubaii/script-deface-creator
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://guthub.com/derv82/wifite
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/8
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/8
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi

if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/9
fi