#!/bin/bash
#dont_recode
#JADILAH ORANG YG RAJIN, JANGAN SUKA PLAGIATIN PUNYA ORANG
#JADILAH GENERASI YG BERKARYA BUKAN GENERASI YG BE4KARYA DENGAN KARYA ORANG LAIN
#JIKA KAMU CUMA BISA COPAS DAN RECODE TOOLS ORANG, KAMU TIDAK AKAN MENDAPATKAN PENGALAMAN
#YANG KAMU DAPATKAN HANYALAH PENGALAMAN COPAS DAN PLAGIATIN TOOLS ORANG LAIN

clear

black='\033[30;0m'
red='\033[31;0m'
green='\033[32;0m'
brown='\033[33;0m'
blue='\033[34;0m'
purple='\033[35;0m'
cyan='\033[36;0m'
gray='\033[37;0m'
dgray='\033[30;1m'
lred='\033[31;1m'
lime='\033[32;1m'
yellow='\033[33;1m'
lblue='\033[34;1m'
lpurple='\033[35;1m'
lcyan='\033[36;1m'
white='\033[37;1m'

clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "==============================================" | lolcat
echo "PILIH TOOLS YANG MAU DI INSTALL" | lolcat
echo $lred"PAGE" $white"10"
echo "==============================================" | lolcat
echo $lred"1." $white "CRAZY-SPAM"
echo $lred"2." $white "RUS"
echo $lred"3." $white "SPAM-TRI"
echo $lred"4." $white "DEVPLOIT"
echo $lred"5." $white "SQL-MATE"
echo $lred"6." $white "STRIKER"
echo $lred"7." $white "PENTESTER"
echo $lred"8." $white "X-GANS"
echo $lred"9." $white "SQL-DUMP"
echo $lred"10." $white"RANG3R"
echo $lred"11." $white"TERMUX-SUDO"
echo $lred"12." $white"EVIL-CREATE-FRAMEWORK"
echo $lred"13." $white"PASS-GEN"
echo $lred"14." $white"SNITCH"
echo $lred"15." $white"HASHER-DOT-ID"
echo $lred"16." $white"NAME-CHK"
echo $lred"17." $white"BEAN-SHELL"
echo $lred"18." $white"MSF-PG"
echo $lred"19." $white"TOUCH-URL"
echo $lred"20." $white"WEEVELY"
echo $lred"21." $white"TERMUX-ARCHLINUX"
echo $lred"22." $white"BLUE-MAHO"
echo $lred"23." $white"BLUE-POT"
echo $lred"24." $white"MAILER-CLI"
echo $lred"25." $white"WFD-INSTALL"
echo "=============================================" | lolcat
echo $lred"0." $white"EXIT"
echo $lred"98." $white"INFO"
echo $lred"a." $white "page 1"
echo $lred"b." $white "page 2"
echo $lred"c." $white "page 3"
echo $lred"d." $white "page 4"
echo $lred"e." $white "page 5"
echo $lred"f." $white "page 6"
echo $lred"g." $white "page 7"
echo $lred"h." $white "page 8"
echo $lred"i." $white "page 9"
echo "=============================================" | lolcat
echo $lcyan
read -p "╭─Zhu-Bai-Lee-tools
╰─> " a;

if [ $a = 1 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
pkg install figlet
pkg install toilet
git clone https://github.com/CrazyError/CS
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 2 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt update && apt upgrade
pkg install curl
pkg install figlet
pkg install python2
pkg install ruby
pkg install gem
pip2 install lolcat
git clone https://github.com/Rusmana-ID/rus
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 3 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/hatakecnk/SPAMTRI2
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 4 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2 git && pip2 install urllib2
git clone https://github.com/joker25000/Devploit
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 5 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install python2
pip2 install mechanize bs4 HTMLparser argparse requests urlparse
git clone https://github.com/UltimateHackers/sqlmate
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 6 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/UltimateHackers/Striker
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 7 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/mrcakil/PentesTer
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 8 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2 
pkg install curl
curl -O http://override.waper.co/files/xgans.txt
mv xgans.txt $HOME
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 9 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2 curl
pip2 install google
curl -k -O https://gist.githubusercontent.com/Gameye98/76076c9a282a6f32749894d5368024a6/raw/6f9e754f2f81ab2b8efda30603dc8306c65bd651/sqldump.py
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 10 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2 && pip2 install optparse termcolor
git clone https://github.com/floriankunushevci/rang3r
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 11 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt install ncurses-utils
git clone https://github.com/st42/termux-sudo
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 12 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/LOoLzeC/Evil-create-framework
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 13 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install php
git clone https://github.com/Cvar1984/PassGen
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 14 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/Smaash/snitch
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 15 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python2
git clone https://github.com/galauerscrew/hasherdotid
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 16 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/HA71/Namechk
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 17 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install dpkg wget
wget https://github.com/amsitlab/amsitlab.github.io/raw/master/dists/termux/amsitlab/binary-all/beanshell_2.04_all.deb
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 18 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/haxzsadik/MSF-Pg
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 19 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install python && pip install parse colorama
git clone https://github.com/SkyKnight-Team/TouchUrl
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 20 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/glides/Weevely
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 21 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone https://github.com/sdrausty/termux-archlinux.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 22 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone git://git.kali.org/packages/bluemaho.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 23 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
git clone git://git.kali.org/packages/bluepot.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 24 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
apt-get update && apt-get upgrade
apt-get install php5-cli
curl -sS https://getcomposer.org/installer | php
chmod +x composer.phar
sudo mv composer.phar /usr/bin/composer
git clone https://github.com/pedro-stanaka/mailer-cli.git
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 25 ]
then
clear
echo "menginstall..." | lolcat
sleep 0.5
pkg install wget
wget https://raw.githubusercontent.com/bytezcrew/wfdroid-termux/master/wfdinstall
echo "done!" | lolcat
sleep 0.5
clear
sh $HOME/zbl/9
fi

if [ $a = 0 ]
then
clear
echo "tunggu 3 detik untuk keluar" | lolcat
sleep 1
clear
toilet -f pagga --metal 3
sleep 1
clear
toilet -f pagga --metal 2
sleep 1
clear
toilet -f pagga --metal 1
sleep 1
clear
toilet -f ivrit -F gay "GooD ByE"
sleep 1
clear
exit
clear
fi

if [ $a = 98 ]
then
clear
toilet -f pagga -F border -F metal "ZBLTOOLS"
echo $yellow"Author: " $lime"Zhu" $lred"Bai" $white"Lee"
echo $white"TEAM: " $lime"SYNDICATE//404" $lred"&" $lime"XFRIEND CYBER TEAM"
echo $yellow"contact me: " $white"+62" $lred"822-1588-5532"
sleep 0.8
echo "\n"
echo "==============================================" | lolcat
toilet -f ivrit -F border -F metal "SPECIAL THANK TO:"
echo $yellow"ALLAH SUBHANAHU WA TA'ALA"
echo $lblue"ALL MEMBER XFRIEND CYBER TEAM"
echo $lime"ALL MEMBER TERMUX TOOLS-ID"
echo $lred"ALL MEMBER SYNDICATE // 404: "
echo $white"Mr.C4TUR"
echo $white"APRILI"
echo $white"WHITESYSTEM/404"
echo $white"YUAN SANDRA"
echo $white"X3nx3"
echo "==============================================" | lolcat
sleep 5
sh $HOME/zbl/9
fi

if [ $a = a ]
then
clear
sh $HOME/zbl/zbltools.sh
fi

if [ $a = b ]
then
clear
sh $HOME/zbl/1
fi
                                                                                                      if [ $a = c ]
then
clear
sh $HOME/zbl/2
fi

if [ $a = d ]
then
clear
sh $HOME/zbl/3
fi

if [ $a = e ]
then
clear
sh $HOME/zbl/4
fi

if [ $a = f ]
then
clear
sh $HOME/zbl/5
fi

if [ $a = g ]
then
clear
sh $HOME/zbl/6
fi

if [ $a = h ]
then
clear
sh $HOME/zbl/7
fi

if [ $a = i ]
then
clear
sh $HOME/zbl/8
fi